### ISSUE TITLE
npm run start fails

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [Unleash/unleash-frontend#180]
npm run start fails with the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/ec2-user/.nvm/versions/node/v10.16.0/bin/node',
1 verbose cli   '/home/ec2-user/.nvm/versions/node/v10.16.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle unleash-frontend@3.2.4~prestart: unleash-frontend@3.2.4
6 info lifecycle unleash-frontend@3.2.4~start: unleash-frontend@3.2.4
7 verbose lifecycle unleash-frontend@3.2.4~start: unsafe-perm in lifecycle true
8 verbose lifecycle unleash-frontend@3.2.4~start: PATH: /home/ec2-user/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-$
9 verbose lifecycle unleash-frontend@3.2.4~start: CWD: /home/ec2-user/unleash-frontend
10 silly lifecycle unleash-frontend@3.2.4~start: Args: [ '-c',
10 silly lifecycle   'NODE_ENV=development webpack-dev-server --progress --colors' ]
11 info lifecycle unleash-frontend@3.2.4~start: Failed to exec start script
12 verbose stack Error: unleash-frontend@3.2.4 start: `NODE_ENV=development webpack-dev-server --progress --colors`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/home/ec2-user/.nvm/versions/node/v10.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48$
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid unleash-frontend@3.2.4
14 verbose cwd /home/ec2-user/unleash-frontend
15 verbose Linux 4.14.114-83.126.amzn1.x86_64
16 verbose argv "/home/ec2-user/.nvm/versions/node/v10.16.0/bin/node" "/home/ec2-user/.nvm/versions/node/v10.16.0/bin/npm" "run" "start"
17 verbose node v10.16.0
18 verbose npm  v6.9.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error unleash-frontend@3.2.4 start: `NODE_ENV=development webpack-dev-server --progress --colors`
23 error spawn ENOENT
24 error Failed at the unleash-frontend@3.2.4 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by Dynatrace-Adam-Gardner** [comment]
Running `npm install` before `npm run start` fixed this.
Will create a PR for a doc update.
